test

diff --git a/.github/workflows/checks.yml b/.github/workflows/checks.yml
--- a/.github/workflows/checks.yml
+++ b/.github/workflows/checks.yml
@@ -19,13 +19,14 @@ jobs:
         run: make
       - name: Run tests
         run: |
-          while IFS= read -r line; do
-          echo "$line" | ./etapa1
-          exit_code=$?
-          if [ $exit_code -eq 1 ] || [ $exit_code -eq 2 ]; then
-            echo "Failed: $line"
-            exit 1
-          fi
+          while IFS= read -r line
+          do
+            echo "$line" | ./etapa1
+            if [ $? -eq 1 ] || [ $? -eq 2 ]; then
+              echo "Failed on input: $line"
+              EXIT_CODE=1
+            fi
           done < tests/success_etapa1.txt
+          exit ${EXIT_CODE}
       - name: Clean up
         run: make clean
