test approach

diff --git a/.github/workflows/checks.yml b/.github/workflows/checks.yml
--- a/.github/workflows/checks.yml
+++ b/.github/workflows/checks.yml
@@ -37,13 +37,12 @@ jobs:
               exit_code="0"
             fi
 
-            ./etapa2 < "$filename"
+            ./etapa2 < "$filename" || echo -e "${RED}FAIL ${NC}$filename"
 
             if [ "$?" -eq "$exit_code" ]; then
               echo -e "${GREEN}PASS ${NC}$filename"
               SUCCESS_COUNT=$(($SUCCESS_COUNT + 1))
             else
-              echo -e "${RED}FAIL ${NC}$filename"
               ERR_COUNT=$(($ERR_COUNT + 1))
             fi
           done
