fix gh action

diff --git a/.github/workflows/checks.yml b/.github/workflows/checks.yml
--- a/.github/workflows/checks.yml
+++ b/.github/workflows/checks.yml
@@ -4,28 +4,25 @@ on:
   push:
     branches:
       - main
-
   pull_request:
     branches:
       - main
 
-  jobs:
-    etapa1:
-      runs-on: ubuntu-latest
-      steps:
-        - name: Checkout repository
-          uses: actions/checkout@v2
-
-        - name: Build files
-          run: make
-          
-        - name: Run tests
-          run: |
-            ./etapa1 < input.txt
-            if [ $? -eq 1 ] || [ $? -eq 2 ]; then
-              echo "Failed"
-              exit 1
-            fi
-
-        - name: Clean up
-          run: make clean
+jobs:
+  etapa1:
+    name: (etapa1) tests
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v2
+      - name: Build files
+        run: make
+      - name: Run tests
+        run: |
+          ./etapa1 < input.txt
+          if [ $? -eq 1 ] || [ $? -eq 2 ]; then
+            echo "Failed"
+            exit 1
+          fi
+      - name: Clean up
+        run: make clean
