test

diff --git a/.github/workflows/checks.yml b/.github/workflows/checks.yml
--- a/.github/workflows/checks.yml
+++ b/.github/workflows/checks.yml
@@ -31,18 +31,20 @@ jobs:
             TOTAL_TESTS=$(($TOTAL_TESTS + 1))
             if grep -q '//FAIL' "$filename"; then
               expected="FAIL"
-              exit_code="1"
+              output_fail=true
             else
               expected="PASS"
-              exit_code="0"
+              output_fail=false
             fi
 
-            ./etapa2 < "$filename" || true
-            result=$?
+            output=$(./etapa2 < "$filename" || true)
+            if echo $output | grep -q "line"; then
+              error=true
+            else
+              error=false
+            fi
 
-            echo "$result $exit_code $filename"
-
-            if [ "$result" -eq "$exit_code" ]; then
+            if { [ "$expected" = "PASS" ] && [ "$error" = false ]; } || { [ "$expected" = "FAIL" ] && [ "$error" = true ]; }; then
               echo -e "${GREEN}PASS ${NC}$filename"
               SUCCESS_COUNT=$(($SUCCESS_COUNT + 1))
             else
